### ISSUE TITLE
Conditional Clarification about Proj

### ISSUE THREAD

**Issue by kamalbuilds** [oceans404/wfa#1]
Hey Steph,

Pretty nice idea but does this also mean that If my wallet gets hacked , the hacker would enter into all my socials too ?

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by oceans404** [comment]
Thank you! No, if your wallet get hacked, the hacker has at most, only your 2nd factor auth (the OTP).

A hacker would need to find every individual social password + your wallet (for OTP) to enter your social accounts.
